# Generated by Django 3.1 on 2020-08-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='profile',
        ),
    ]
