# Generated by Django 3.1 on 2020-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_emails_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
