# Generated by Django 3.1 on 2020-08-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
